USE [master]
GO

/****** Object:  Database [SmartFarningDB]    Script Date: 2021-08-04 02:11:57 PM ******/
CREATE DATABASE [SmartFarningDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SmartFarningDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SmartFarningDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SmartFarningDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SmartFarningDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SmartFarningDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SmartFarningDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SmartFarningDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SmartFarningDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SmartFarningDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SmartFarningDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SmartFarningDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SmartFarningDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SmartFarningDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SmartFarningDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SmartFarningDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SmartFarningDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SmartFarningDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SmartFarningDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SmartFarningDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SmartFarningDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SmartFarningDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SmartFarningDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SmartFarningDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SmartFarningDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SmartFarningDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SmartFarningDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SmartFarningDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SmartFarningDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SmartFarningDB] SET RECOVERY FULL 
GO

ALTER DATABASE [SmartFarningDB] SET  MULTI_USER 
GO

ALTER DATABASE [SmartFarningDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SmartFarningDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SmartFarningDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SmartFarningDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SmartFarningDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SmartFarningDB] SET QUERY_STORE = OFF
GO

USE [SmartFarningDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SmartFarningDB] SET  READ_WRITE 
GO


